library(dplyr)
library(sp)
source("501_OD_processing_functions.R")

#convertendo para sp - na origem da viagem e no destino da viagem
#viagens de transporte motorizado (carro, proprio ou 'alugado')
database_privado_origem <- convert_spatial(database_privado, origem = T)
database_privado_destino <- convert_spatial(database_privado, origem = F)
rm(database_privado)
#viagens de transporte motorizado (moto, dirigindo ou passageiro)
database_privado_moto_origem <- convert_spatial(database_privado_moto, origem = T)
database_privado_moto_destino <- convert_spatial(database_privado_moto, origem = F)
rm(database_privado_moto)
#viagens de transporte público - todos os modais (sem fretados privados e sem transporte escolar)
database_publico_origem <- convert_spatial(database_publico, origem = T)
database_publico_destino <- convert_spatial(database_publico, origem = F)
rm(database_publico)
#viagens de transporte fretados privados
database_fretados_origem <- convert_spatial(database_fretados, origem = T)
database_fretados_destino <- convert_spatial(database_fretados, origem = F)
rm(database_fretados)
#viagens de transporte escolar
database_escolar_origem <- convert_spatial(database_escolar, origem = T)
database_escolar_destino <- convert_spatial(database_escolar, origem = F)
rm(database_escolar)